/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;



import Business.Enterprise.AdoptionEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FosterCaringEnterpris;
import Business.Enterprise.FundingEnterprise;

import Business.Enterprise.HosEnterprices;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrgDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrgDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer,OrgDirectory directory, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        this.enterprise=enterprise;
        populateTable();
        //populateCombos();
         orgxombobox.removeAllItems();
        if(enterprise instanceof HosEnterprices){
             orgxombobox.addItem(Type.Doctor);
               orgxombobox.addItem(Type.Lab);
               orgxombobox.addItem(Type.Pharmacist);
        }
        if(enterprise instanceof FosterCaringEnterpris){
          orgxombobox.addItem(Type.ChildCare);
               orgxombobox.addItem(Type.ChildRegistration);
        }
        if(enterprise instanceof AdoptionEnterprise){
           //organizationJComboBox.addItem(Type.Adopter);
               orgxombobox.addItem(Type.Adoption);
               orgxombobox.addItem(Type.FinanceCheck); 
                 orgxombobox.addItem(Type.CriminalCheck); 
        }
        if(enterprise instanceof FundingEnterprise){
           orgxombobox.addItem(Type.FinanceOrganization);
               //organizationJComboBox.addItem(Type.Donor);
               
        }
    }
    
    private void populateCombo(){
        orgxombobox.removeAllItems();
       
        for (Type type : Organization.Type.values()){
            if (!type.getValue().equals(Type.Admin.getValue()))
                orgxombobox.addItem(type);
        }
    }
    
    

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tableorg.getModel();
        model.setRowCount(0);
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getType();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableorg = new javax.swing.JTable();
        addorgbox = new javax.swing.JButton();
        orgxombobox = new javax.swing.JComboBox();
        orgtype = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        orgnamebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableorg.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tableorg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Type", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableorg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 680, 130));

        addorgbox.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addorgbox.setText("Add Organization");
        addorgbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorgboxActionPerformed(evt);
            }
        });
        add(addorgbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 150, 33));

        add(orgxombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 210, 40));

        orgtype.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        orgtype.setText("Organization Type ");
        add(orgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, 35));

        name.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        name.setText("Name");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        orgnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgnameboxActionPerformed(evt);
            }
        });
        add(orgnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/org.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 640, 570));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANAGE ORGANIZATION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 370, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addorgboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorgboxActionPerformed
        Type type = (Type) orgxombobox.getSelectedItem();
        if ("".equals(orgnamebox.getText())) {
            JOptionPane.showMessageDialog(null, "Enter organization name!");
        } else {
            if (directory.isUnique(orgnamebox.getText())) {
                directory.createOrganization(orgnamebox.getText(), type);
                JOptionPane.showMessageDialog(null, "Organization Successfully Created");
                orgnamebox.setText("");
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Organization name already exists!");
            }

        }

    }//GEN-LAST:event_addorgboxActionPerformed

    private void orgnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgnameboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addorgbox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField orgnamebox;
    private javax.swing.JLabel orgtype;
    private javax.swing.JComboBox orgxombobox;
    private javax.swing.JTable tableorg;
    // End of variables declaration//GEN-END:variables
}
