/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrgDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    private OrgDirectory organizationDir;
    private JPanel userProcessContainer;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageEmployeeJPanel(JPanel userProcessContainer,OrgDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }
    
    public void populateOrganizationComboBox() {
        BOXORGANIZATION.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            BOXORGANIZATION.addItem(organization);
        }
    }

    public void populateOrganizationEmpComboBox() {
        organizationEmploye.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            organizationEmploye.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) TABLEORGANZ.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TABLEORGANZ = new javax.swing.JTable();
        createaddbuton = new javax.swing.JButton();
        BOXORGANIZATION = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametextfield = new javax.swing.JTextField();
        organizationEmploye = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TABLEORGANZ.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TABLEORGANZ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TABLEORGANZ);
        if (TABLEORGANZ.getColumnModel().getColumnCount() > 0) {
            TABLEORGANZ.getColumnModel().getColumn(0).setResizable(false);
            TABLEORGANZ.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 590, 128));

        createaddbuton.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        createaddbuton.setText("Create Employee");
        createaddbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaddbutonActionPerformed(evt);
            }
        });
        add(createaddbuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 180, 33));

        BOXORGANIZATION.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        BOXORGANIZATION.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BOXORGANIZATION.setMinimumSize(new java.awt.Dimension(64, 20));
        BOXORGANIZATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOXORGANIZATIONActionPerformed(evt);
            }
        });
        add(BOXORGANIZATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 277, 35));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("View Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Employee Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 130, 34));

        nametextfield.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        add(nametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 227, 34));

        organizationEmploye.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        organizationEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmployeActionPerformed(evt);
            }
        });
        add(organizationEmploye, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 320, 230, 35));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 106, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 690, 430));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MANAGE EMPLOYEE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 400, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createaddbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaddbutonActionPerformed
         if (!nametextfield.getText().equals("")) {
            Organization organization = (Organization) organizationEmploye.getSelectedItem();
            String name = nametextfield.getText();
            organization.getEmployeeDirectory().createEmployee(name);
            JOptionPane.showMessageDialog(null,"Employee Added Successfully");
            populateTable(organization);
            nametextfield.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Enter value", "Warning", JOptionPane.WARNING_MESSAGE);
        }     
        
    }//GEN-LAST:event_createaddbutonActionPerformed

    private void BOXORGANIZATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOXORGANIZATIONActionPerformed
        Organization organization = (Organization) BOXORGANIZATION.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_BOXORGANIZATIONActionPerformed

    private void organizationEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationEmployeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BOXORGANIZATION;
    private javax.swing.JTable TABLEORGANZ;
    private javax.swing.JButton createaddbuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametextfield;
    private javax.swing.JComboBox organizationEmploye;
    // End of variables declaration//GEN-END:variables
}
