/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UAcc.UAcc;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anushree_j
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private EcoSystem ecosystem;

    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;
        this.ecosystem = ecosystem;
        popOrganizationComboBox();
        popData();
    }

    public void popOrganizationComboBox() {
        orgright.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            orgright.addItem(organization);
        }
    }

    public void populateEmployeeComboBox(Organization organization) {
        empright.removeAllItems();

        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
            empright.addItem(employee);
        }
    }

    private void populateRoleComboBox(Organization organization) {
        roleright.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            roleright.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) usertablebox.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UAcc ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) usertablebox.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createUserJButtonclick = new javax.swing.JButton();
        usernameright = new javax.swing.JTextField();
        usernameleft = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertablebox = new javax.swing.JTable();
        passwordleft = new javax.swing.JLabel();
        passwordtextright = new javax.swing.JTextField();
        empleft = new javax.swing.JLabel();
        empright = new javax.swing.JComboBox();
        orgleft = new javax.swing.JLabel();
        orgright = new javax.swing.JComboBox();
        roleleft = new javax.swing.JLabel();
        roleright = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createUserJButtonclick.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createUserJButtonclick.setText("Create");
        createUserJButtonclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserJButtonclickActionPerformed(evt);
            }
        });
        add(createUserJButtonclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 133, 33));

        usernameright.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(usernameright, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 200, 35));

        usernameleft.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        usernameleft.setText("User Name");
        add(usernameleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 89, 35));

        usertablebox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        usertablebox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usertablebox);
        if (usertablebox.getColumnModel().getColumnCount() > 0) {
            usertablebox.getColumnModel().getColumn(0).setResizable(false);
            usertablebox.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 680, 140));

        passwordleft.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        passwordleft.setText("Password");
        add(passwordleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 89, 35));

        passwordtextright.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(passwordtextright, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 200, 35));

        empleft.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        empleft.setText("Employee");
        add(empleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 105, 35));

        empright.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        add(empright, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 200, 30));

        orgleft.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        orgleft.setText("Organization");
        add(orgleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 105, 34));

        orgright.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        orgright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgrightActionPerformed(evt);
            }
        });
        add(orgright, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 200, 30));
        orgright.getAccessibleContext().setAccessibleName("");

        roleleft.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        roleleft.setText("Role");
        add(roleleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 66, 35));

        roleright.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        add(roleright, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 200, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user background.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 570, 560));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MANAGE USER ACCOUNT");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 420, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserJButtonclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButtonclickActionPerformed
        String userName = usernameright.getText();
        String password = passwordtextright.getText();
        if ("".equals(userName)) {
            JOptionPane.showMessageDialog(null, "Please enter username");
        } else if (!ecosystem.checkIfUserIsUnique(userName)) {
            JOptionPane.showMessageDialog(null, "Please enter unique username");
        } else if ("".equals(password)) {
            JOptionPane.showMessageDialog(null, "Please enter password");
        } else {
            Organization organization = (Organization) orgright.getSelectedItem();
            Employee employee = (Employee) empright.getSelectedItem();
            Role role = (Role) roleright.getSelectedItem();
            organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
            JOptionPane.showMessageDialog(null, "User Account Created");
            usernameright.setText("");
            passwordtextright.setText("");
            popData();
        }
    }//GEN-LAST:event_createUserJButtonclickActionPerformed

    private void orgrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgrightActionPerformed
        Organization organization = (Organization) orgright.getSelectedItem();
        if (organization != null) {
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
            usernameright.setText("");
            passwordtextright.setText("");
        }
    }//GEN-LAST:event_orgrightActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserJButtonclick;
    private javax.swing.JLabel empleft;
    private javax.swing.JComboBox empright;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgleft;
    private javax.swing.JComboBox orgright;
    private javax.swing.JLabel passwordleft;
    private javax.swing.JTextField passwordtextright;
    private javax.swing.JLabel roleleft;
    private javax.swing.JComboBox roleright;
    private javax.swing.JLabel usernameleft;
    private javax.swing.JTextField usernameright;
    private javax.swing.JTable usertablebox;
    // End of variables declaration//GEN-END:variables
}
