/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Adoption.BGCandCriminalCheck;

import Business.Adopter.Adopter;
import Business.Adopter.AdpDirec;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BackgroundAndCriminalCheckOrganization;
import Business.Organization.FinanceCheckOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.CommonMail;
import Business.WorkQueue.AdopterStatusCheckWorkRequest;
import Business.WorkQueue.BGVProcessWorkRequest;
import Business.WorkQueue.FinanceCheckProcessWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class BGCandCriminalProcess extends javax.swing.JPanel {

    /**
     * Creates new form BGCandCriminalProcess
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem business;
    AdpDirec adopterdirectory;
    BackgroundAndCriminalCheckOrganization bgcOrganization;
    Adopter adopter;
    BGVProcessWorkRequest bgcWorkRequest;
    
    public BGCandCriminalProcess(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, AdpDirec adopterdirectory, BGVProcessWorkRequest bgcWorkRequest, Adopter adopter) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.adopterdirectory=adopterdirectory;
        this.account=account;
        this.enterprise=enterprise;
        this.business = business;
        this.bgcOrganization = (BackgroundAndCriminalCheckOrganization)organization;
        this.bgcWorkRequest = bgcWorkRequest;
        this.adopter = adopter;
        populateWorkRequest();
        setUserDetailsField();
        
        nametext.setEnabled(false);
        agetext.setEnabled(false);
        ssntextbox.setEnabled(false);
        maleclcikdrop.setEnabled(false);
        femaleclickdrop.setEnabled(false);
        incomeforbackcheck.setEnabled(false);
        emailidforback.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backcrimecheckprocessing = new javax.swing.JLabel();
        adopterlabeldetials = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        ssnlabell = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        labelincome = new javax.swing.JLabel();
        emailidforback = new javax.swing.JTextField();
        nametext = new javax.swing.JTextField();
        agetext = new javax.swing.JTextField();
        ssntextbox = new javax.swing.JTextField();
        incomeforbackcheck = new javax.swing.JTextField();
        maleclcikdrop = new javax.swing.JRadioButton();
        femaleclickdrop = new javax.swing.JRadioButton();
        tablebackandcrime = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        remarks = new javax.swing.JLabel();
        textforremarks = new javax.swing.JTextField();
        approvebutton = new javax.swing.JButton();
        deny = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backcrimecheckprocessing.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        backcrimecheckprocessing.setText("BACKGROUND AND CRIMINAL CHECK PROCESS");
        add(backcrimecheckprocessing, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        adopterlabeldetials.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        adopterlabeldetials.setText("ADOPTER DETAILS");
        add(adopterlabeldetials, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 20));

        lblEmail.setText("Email ID");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 90, 20));

        namelabel.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        namelabel.setText("Name");
        add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 20));

        agelabel.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        agelabel.setText("Age");
        add(agelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 20));

        ssnlabell.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        ssnlabell.setText("SSN");
        add(ssnlabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 110, 20));

        genderlabel.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        genderlabel.setText("Gender");
        add(genderlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 110, 20));

        labelincome.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        labelincome.setText("Income");
        add(labelincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 90, 20));
        add(emailidforback, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 180, -1));

        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });
        add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, -1));
        add(agetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 190, -1));
        add(ssntextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 190, -1));
        add(incomeforbackcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 180, 30));

        maleclcikdrop.setText("Male");
        add(maleclcikdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 70, -1));

        femaleclickdrop.setText("Female");
        add(femaleclickdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        tblRequest.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Adopter ID", "Adopter Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablebackandcrime.setViewportView(tblRequest);

        add(tablebackandcrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 850, 160));

        remarks.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        remarks.setText("Remarks");
        add(remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 90, -1));

        textforremarks.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        textforremarks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(textforremarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 210, 70));

        approvebutton.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        approvebutton.setText("Approve");
        approvebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvebuttonActionPerformed(evt);
            }
        });
        add(approvebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 140, -1));

        deny.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        deny.setText("Deny");
        deny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyActionPerformed(evt);
            }
        });
        add(deny, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 830, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void approvebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvebuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the request to proceed.");
            return;
        }

        Object statusval = tblRequest.getValueAt(selectedRow, 5);
        Object receiverval = tblRequest.getValueAt(selectedRow, 2);

        if ("Approved".equals(statusval) || "Denied".equals(statusval)) {
            JOptionPane.showMessageDialog(null, "Request already processed");
        } else {

            if (receiverval.equals(account.getUsername())) {

                BGVProcessWorkRequest request = (BGVProcessWorkRequest) tblRequest.getValueAt(selectedRow, 0);
                request.setStatus("Approved");
                request.setComment(textforremarks.getText());
                request.setUserId(adopter.getUserId());
                request.setBgcStatus("Approved");
                populateWorkRequest();
                FinanceCheckProcessWorkRequest fcwreq = new FinanceCheckProcessWorkRequest();
                fcwreq.setMessage("Please initiate Finance check");
                fcwreq.setStatus("Pending with Finance organization");
                fcwreq.setSender(account);
                fcwreq.setUserId(adopter.getUserId());
                fcwreq.setName(adopter.getName());

                Organization org = null;
                for (Network network : business.getNetworkList()) {
                    for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof FinanceCheckOrganization) {
                                org = organization;
                                break;
                            }
                        }
                    }
                }

                if (org != null) {
                    org.getWorkQueue().getWorkRequestList().add(fcwreq);
                    account.getWorkQueue().getWorkRequestList().add(fcwreq);
                    business.getWorkQueue().getWorkRequestList().add(fcwreq);
                }

                for (WorkRequest req : business.getWorkQueue().getWorkRequestList()) {
                    if (req.getUserId() == adopter.getUserId()) {
                        if (req instanceof AdopterStatusCheckWorkRequest) {
                            ((AdopterStatusCheckWorkRequest) req).setFinanceStatus("Pending");
                            ((AdopterStatusCheckWorkRequest) req).setBgcStatus("Approved");
                            ((AdopterStatusCheckWorkRequest) req).setMessage("Finance check initialized");
                        }
                    }
                }
                String subject = "Background Check Approved";
                String content = "Your background check has been completed and approved. The request is further sent to Finance check team .You can confirm your status through portal. \nThank you";
                CommonMail.sendEmailMessage(adopter.getEmailId(), subject, content);
                JOptionPane.showMessageDialog(null, "Finance check initialized successfully!");

            } else {
                JOptionPane.showMessageDialog(null, "Please select work request assigned to you");
            }
            textforremarks.setText("");
        }
    }//GEN-LAST:event_approvebuttonActionPerformed

    private void denyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the request to proceed.");
            return;
        }

        Object statusval = tblRequest.getValueAt(selectedRow, 5);
        Object receiverval = tblRequest.getValueAt(selectedRow, 2);
        if ("Approved".equals(statusval) || "Denied".equals(statusval)) {
            JOptionPane.showMessageDialog(null, "Request already processed");
        } else {
            if (receiverval.equals(account.getUsername())) {

                BGVProcessWorkRequest request = (BGVProcessWorkRequest) tblRequest.getValueAt(selectedRow, 0);

                request.setStatus("Denied");
                request.setComment(textforremarks.getText());
                request.setSender(account);
                request.setUserId(adopter.getUserId());
                request.setBgcStatus("Denied");
                populateWorkRequest();

                for (WorkRequest req : business.getWorkQueue().getWorkRequestList()) {
                    if (req.getUserId() == adopter.getUserId()) {
                        if (req instanceof AdopterStatusCheckWorkRequest) {
                            if (((AdopterStatusCheckWorkRequest) req).getFinanceStatus().equals("Pending")) {
                                ((AdopterStatusCheckWorkRequest) req).setFinanceStatus("Cancelled");
                                ((AdopterStatusCheckWorkRequest) req).setBgcStatus("Denied");
                                ((AdopterStatusCheckWorkRequest) req).setMessage("BGC Failed.Request cancelled");

                            }
                        }
                    }
                }
                String subject = "Background Verification failed";
                String content = "We are sorry to inform you that your background check has been failed and cannot proceed with adoption procedure .You can confirm your status through portal. \nThank you";
                CommonMail.sendEmailMessage(adopter.getEmailId(), subject, content);
                JOptionPane.showMessageDialog(null, "Background check denied. Adopt request cancelled");
            } else {
                JOptionPane.showMessageDialog(null, "Please select work request assigned to you");
            }
            textforremarks.setText("");
        }
    }//GEN-LAST:event_denyActionPerformed
    
    public void populateWorkRequest() {

        DefaultTableModel dtm = (DefaultTableModel) tblRequest.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : bgcOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof BGVProcessWorkRequest) {
                if (request.getUserId() == bgcWorkRequest.getUserId()) {
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = request;
                    row[1] = request.getSender().getEmployee().getName();
                    row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                    row[3] = request.getUserId();
                    row[4] = request.getName();
                    row[5] = request.getStatus();
                    dtm.addRow(row);
                }
            }
        }
    }

    public void setUserDetailsField() {
        agetext.setText(String.valueOf(adopter.getAge()));
        emailidforback.setText(adopter.getEmailId());
        incomeforbackcheck.setText(String.valueOf(adopter.getAnnualIncome()));
        nametext.setText(adopter.getName());
        ssntextbox.setText(adopter.getSsn());
        if (adopter.getGender().equalsIgnoreCase("male")) {
            maleclcikdrop.setSelected(true);
        } else {
            femaleclickdrop.setSelected(true);
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adopterlabeldetials;
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField agetext;
    private javax.swing.JButton approvebutton;
    private javax.swing.JLabel backcrimecheckprocessing;
    private javax.swing.JButton deny;
    private javax.swing.JTextField emailidforback;
    private javax.swing.JRadioButton femaleclickdrop;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JTextField incomeforbackcheck;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelincome;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JRadioButton maleclcikdrop;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel remarks;
    private javax.swing.JLabel ssnlabell;
    private javax.swing.JTextField ssntextbox;
    private javax.swing.JScrollPane tablebackandcrime;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField textforremarks;
    // End of variables declaration//GEN-END:variables
}
